
# reccaster has moved - https://github.com/ChannelFinder/recsync/pull/169
all:
	@echo ""
	@echo "ERROR: The 'reccaster' module has been moved to its own repository."
	@echo "  New location: https://github.com/channelfinder/reccaster"
	@echo ""
	@echo "  git clone https://github.com/channelfinder/reccaster"
	@echo ""
	@exit 1
